# Generated by Django 5.0.3 on 2024-03-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_identification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualdetails',
            name='year_of_birth',
        ),
        migrations.AddField(
            model_name='individualdetails',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
