# Generated by Django 5.0.3 on 2024-04-03 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_identification', '0002_remove_individualdetails_year_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumarationgeography',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer_identification.individualdetails'),
        ),
    ]
