# Generated by Django 5.0.3 on 2024-04-03 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_holding', '0001_initial'),
        ('farmer_identification', '0002_remove_individualdetails_year_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmholdings',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer_identification.individualdetails'),
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('total_acrage', models.IntegerField()),
                ('unit_area', models.CharField(max_length=100)),
                ('certified_seeds', models.BooleanField()),
                ('purpose', models.CharField(max_length=100)),
                ('water_source', models.CharField(max_length=50)),
                ('crop_system', models.CharField(max_length=100)),
                ('fertilizer', models.BooleanField()),
                ('pestcide', models.BooleanField()),
                ('farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer_identification.individualdetails')),
            ],
        ),
    ]
