# Generated by Django 5.0.3 on 2024-04-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_holding', '0002_farmholdings_farmer_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='certified_seeds',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crop',
            name='fertilizer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crop',
            name='pestcide',
            field=models.CharField(max_length=100),
        ),
    ]
