# Generated by Django 5.0.3 on 2024-04-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_holding', '0003_alter_crop_certified_seeds_alter_crop_fertilizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmholdings',
            name='other_farms',
            field=models.CharField(max_length=50),
        ),
    ]
